name: Deploy NemFit App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Configure .streamlit
        run: |
          mkdir -p ~/.streamlit
          echo "[server]" > ~/.streamlit/config.toml
          echo "headless = true" >> ~/.streamlit/config.toml
          echo "enableCORS = false" >> ~/.streamlit/config.toml
          echo "port = $PORT" >> ~/.streamlit/config.toml
          echo "enableXsrfProtection = false" >> ~/.streamlit/config.toml
          
      - name: Run tests (if any)
        run: |
          echo "Running tests..."
          # Add test commands here if needed
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: .